version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - "/backend/common/"
      - "/backend/console/"
      - "/backend/testing/"
      - "/backend/migration/"
    schedule:
      interval: "weekly"
    labels:
      - "ğŸ“¦ Type: Dependencies"
      - "â³ Status: Waiting for review"
